jira_url: "https://jira.cc.bmwgroup.net/"
test_plans:
  # IDCEVO PU2507 user
  - issue: "IDCEVODEV-409580"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SIT-Automated"

  - issue: "IDCEVODEV-409141"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SI-performance"

  - issue: "IDCEVODEV-409581"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SI-performance-monitoring"

  - issue: "IDCEVODEV-409583"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-kpi-reboots"

  - issue: "IDCEVODEV-409585"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-lifecycle"

  - issue: "IDCEVODEV-409587"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-stability"

  - issue: "IDCEVODEV-409593"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI"

  - issue: "IDCEVODEV-409586"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-long"

  - issue: "IDCEVODEV-409589"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SI-diag"

  - issue: "IDCEVODEV-409590"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SI-android"

  - issue: "IDCEVODEV-409591"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-PDX-flashing-stress"

  - issue: "IDCEVODEV-409595"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-production"

  - issue: "IDCEVODEV-409596"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-SI-Multi-Coding-NA"

  # This job is currently disabled
  # - issue: "IDCEVODEV-438815"
  #   delta_time: 0
  #   fail_rate_delta_time: 7
  #   suite: "IDCEVO-pu2507-user-SI-STR"

  - issue: "IDCEVODEV-443825"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-user-STR-SIT-Automated"

  - issue: "IDCEVODEV-515768"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-pu2507-userdebug-SI-SIT-Automated-domains"

publisher:
  confluence:
    publish: true
    space_key: "idcevo"
    parent_page_name: "IDCEVO PU2507 SIT results"
    title: "PU2507 USER SIT results"
    confluence_wiki: "https://confluence.cc.bmwgroup.net/"
