jira_url: "https://jira.cc.bmwgroup.net/"
test_plans:
  # IDCEVO SP21
  - issue: "IDCEVODEV-301746"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-SP21-SI-SIT-Automated"

  - issue: "IDCEVODEV-301752"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-SP21-SI-performance"

  # This job is currently disabled
  # - issue: "IDCEVODEV-301756"
  #   delta_time: 0
  #   fail_rate_delta_time: 7
  #   suite: "IDCEVO-SP21-SI-stability"

  - issue: "IDCEVODEV-301757"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-SP21-SI"

  # This job is currently disabled
  # - issue: "IDCEVODEV-301760"
  #   delta_time: 0
  #   fail_rate_delta_time: 7
  #   suite: "IDCEVO-SP21-SI-long"

  - issue: "IDCEVODEV-301764"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-SP21-SI-diag"

  - issue: "IDCEVODEV-393637"
    delta_time: 0
    fail_rate_delta_time: 7
    suite: "IDCEVO-SP21-SI-android"

  - issue: "IDCEVODEV-517404"
    delta_time: 0
    fail_rate_delta_time: 14
    suite: "IDCEVO-SP21-SI-Multi-Coding-U"

publisher:
  confluence:
    publish: true
    space_key: "idcevo"
    parent_page_name: "IDCEVO SP21 SIT results"
    title: "IDCEVO SP21 SIT results"
    confluence_wiki: "https://confluence.cc.bmwgroup.net/"
