- name: Collect build information
  hosts: all
  roles:
    - role: zuul-set-log-url
  tasks:
    - name: Define images release info path
      stat:
        path: "{{ test_env_out_dir }}/images_release_info"
      register: images_release_info_path

    - name: Define test artifacts results path
      stat:
        path: "{{ zuul_logs_dir }}/test-artifacts/results"
      register: test_artifacts_results_path

    - block:
        - name: Get image release info
          shell:
            cmd: cat "{{ test_env_out_dir }}/images_release_info"
          register: image_release_info

        - name: Extract gl version
          set_fact:
            gl_version: "{{ image_release_info.stdout | regex_findall('.*([0-9]{2}w[0-9]{2}.[0-9]-[0-9]).*') | first }}"
      when: images_release_info_path.stat.exists

    - block:
        - name: Get hardware revision
          shell:
            cmd: grep -m 1 -o "hardware_revision='[^']*'" "{{ zuul_logs_dir }}/test-artifacts/results/test_{{ product_type }}.log" | awk -F"'" '{print $2}'
          register: hardware_revision_info

        - name: assert that hardware revision is known
          vars:
            supported_revisions:
              - B1
              - B2
              - B3
              - B4
              - C1
              - D1
          assert:
            that:
              - 'hardware_revision_info.stdout in supported_revisions'
            fail_msg: "the hardware revision is not recognized: '{{ hardware_revision_info.stdout }}'"

        - name: Set hardware revision
          set_fact:
            hardware_revision: "{{ product_type }}_{{ hardware_revision_info.stdout | default('hw_unkn') }}"

        - name: Get hardware variant
          shell:
            cmd: grep -m 1 -o "target_serial_no='HBB[0-9]\{1,\}" "{{ zuul_logs_dir }}/test-artifacts/results/test_{{ product_type }}.log" | awk -F"target_serial_no='HB" '{print $2}'
          register: hardware_variant_info

        - name: assert that hardware variant is known
          vars:
            supported_variants:
              # https://confluence.cc.bmwgroup.net/display/idcevo/Hardware+Variants+Overview+-+Simplified
              # IDCEVO SP25
              - B504
              - B505
              - B506
              # IDCEVO SP21
              - B538
              - B539
              - B542
              - B543
              - B544
              - B545
              # CDE
              - B541
              # RSE26
              - B513
          assert:
            that:
              - 'hardware_variant_info.stdout in supported_variants'
            fail_msg: "the hardware variant is not recognized: '{{ hardware_variant_info.stdout }}'"

        - name: Set hardware variant
          set_fact:
            hardware_variant: "{{ hardware_variant_info.stdout | default('variant_unknown') }}"

        - name: Collect job information to env file
          copy:
            content: |
              ansible_host={{ ansible_facts['nodename'] | default('') }}
              artifacts_url={{ zuul_log_url }}test-artifacts/
              build={{ zuul.build }}
              build_short={{ zuul.build[0:7] }}
              build_url={{ codecraft.base_url }}/zuul/t/{{ zuul.tenant }}/build/{{ zuul.build }}
              change_url={{ zuul.change_url | default('') }}
              gl_version={{ gl_version }}
              job={{ zuul.job }}
              job_output={{ zuul_log_url  }}job-output.txt
              job_url={{ codecraft.base_url }}/zuul/t/{{ zuul.tenant }}/build/{{ zuul.build }}
              product_type={{ product_type }}
              result_html={{ zuul_log_url  }}test_results.html
              test_suite={{ tee_test_suite }}
              hardware_revision={{ hardware_revision }}
              hardware_variant={{ hardware_variant }}
              branch={{ branch_node0 }}
              build_type={{ aosp_build_type_ta }}
              job_build_tag={{ zuul.build[0:7] }}
            dest: "{{ zuul_logs_dir }}/test-artifacts/build.env"
            mode: "0644"
      when: test_artifacts_results_path.stat.exists and test_artifacts_results_path.stat.isdir
